### ISSUE TITLE
Error when Linking against OpenMP

### ISSUE THREAD

**Issue by wangyiqiu** [cmuparlay/parlaylib#14]
I was trying to use ParlayLib's algorithm with OpenMP, because I used ParlayLib in a project of ours. A user encountered [segmentation faults](https://github.com/wangyiqiu/hdbscan/issues/4) coming from the scheduler when they try to run the code on `Linux Mint 20.2, X5675 CPU` and `CentOS Stream 9, Dual X5670`. I was thinking a quick workaround is to run the code using an alternative scheduler like OpenMP, but still using ParlayLib's algorithms.

However, when I try to compile with OpenMP, I encountered errors containing:
```
multiple definition of `parlay::in_par_do';
```
I tried to link against OpenMP using multiple repositories using ParlayLib, but got the same error. The error can be reproduced like this:
```
git clone -b openmp https://github.com/ParAlg/ParGeo.git pargeo
cd pargeo
git submodule init
git submodule update
mkdir build
cd build
cmake ..
make -j
```
Specifically, I wasn't sure if my [CMake setting](https://github.com/ParAlg/ParGeo/blob/f5532f0832be2a83178dc734c2bb5ded33a66ce5/CMakeLists.txt#L15) is correct.

Here's the full error message:
```
/usr/bin/ld: ../src/enclosingBall/sampling/libsamplingSebLib.a(seb.cpp.o):(.bss+0x0): multiple definition of `parlay::in_par_do'; CMakeFiles/smallestEnclosingBall.dir/smallestEnclosingBall.cpp.o:(.bss+0x20): first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [example/CMakeFiles/smallestEnclosingBall.dir/build.make:85: example/smallestEnclosingBall] Error 1
make[1]: *** [CMakeFiles/Makefile2:1547: example/CMakeFiles/smallestEnclosingBall.dir/all] Error 2
```

**Comment by DanielLiamAnderson** [comment]
A fix for this will be coming in #21, but we are still investigating a related bug, so it's not quite ready yet. Apologies for the delay, hopefully it will be good soon!

**Comment by DanielLiamAnderson** [comment]
This should be fixed now!

**Comment by wangyiqiu** [comment]
I will tryout the update soon, and let you know we encounter other problems. Thank you Daniel!
