### ISSUE TITLE
Invalid return value of function seq_count_sort

### ISSUE THREAD

**Issue by Akatsukis** [cmuparlay/parlaylib#20]
https://github.com/cmuparlay/parlaylib/blob/a9d999262198354e2afbef46087aadf1e6142102/include/parlay/internal/counting_sort.h#L96
The return value of this function is supposed to be the prefix sum of counts of each key. However, `counts` is modified in the following function to help write back after `seq_count_sort_` is called:
https://github.com/cmuparlay/parlaylib/blob/a9d999262198354e2afbef46087aadf1e6142102/include/parlay/internal/counting_sort.h#L68
A quick fix to this issue is to make a copy of `counts` such that it stays unmodified. However, this fix turned out being slower than the parallel version on my end :(

**Comment by gblelloch** [comment]
I'm not sure I understand the issue.   I'm probably missing something, but
to me seq_write_down seems correct.   In particular before the call the
sequence offsets should contain the "inclusive" sum of all previous buckets
+ the bucket itself.   After  the loop it should contain the "exclusive"
sum (scan) of all previous buckets, but not the bucket itself.

Could you give an example of where the result of counting sort is incorrect?

Thanks,
Guy
