### ISSUE TITLE
could not convert ‘a’ from ‘parlay::sequence<long unsigned int>’ to ‘parlay::sequence<unsigned int>’

### ISSUE THREAD

**Issue by Ashelyed** [cmuparlay/parlaylib#26]
Does the sorting algorithm not support the "long unsigned int" ?

**Comment by Ashelyed** [comment]
when i use the sorting algorithm parlay::integer_sort(key); the key is parlay::sequence<uint64_t> key; and then the error occur

**Comment by DanielLiamAnderson** [comment]
Thanks for the report. Could you please provide more information?

- Operating system and version
- Compiler and version
- A specific minimal code example that reproduces the bug
