### ISSUE TITLE
Control number of threads in runtime.

### ISSUE THREAD

**Issue by jsboer** [cmuparlay/parlaylib#29]
Hi, I know that we can control number of threads by environment `PARLAY_NUM_THREADS`， but how to conrol it in  runtime? for example, there are two parallel_for in main(), I want them to use different number of threads.

**Comment by DanielLiamAnderson** [comment]
Hey,

At present, we do not have this kind of capability, but it is something that we would like to add in the future!

**Comment by jsboer** [comment]
Ok, thank you!
