### ISSUE TITLE
sometimes encounter ”Assertion `new_size <= capacity()' failed“

### ISSUE THREAD

**Issue by jsboer** [cmuparlay/parlaylib#31]
Hi，I use g++ 10.2.0 with parlay-master, sometimes program will run correctly, but sometimes it will complain one of these two errors. what could cause this?

```
/sequence_base.h:463: 
void parlay::sequence_internal::sequence_base<T, Allocator, EnableSSO>::storage_impl::set_size(size_t) [with T = unsigned int; Allocator = parlay::allocator<unsigned int>; bool EnableSSO = false; size_t = long unsigned int]: Assertion `new_size <= capacity()' failed.
```

or sometimes

```
free(): invalid pointer: 0x00002b8af6a08470 ***
```

**Comment by DanielLiamAnderson** [comment]
Looks like an issue with allocating memory for sequences.

Could you post a minimal reproducible code example that causes these issues?

**Comment by jsboer** [comment]
> Looks like an issue with allocating memory for sequences.
> 
> Could you post a minimal reproducible code example that causes these issues?

Hi, it seems to be push_back error. This error will be removed when no longer multi-thread push_back for a same sequence.
like 
```
sequence<size_t> a;
parallel_for(0,n,[](size_t i){ a.push_back(i)};
```
Does sequence support concurrent push_back? I find this will cause wrong result, say ```a.size()!=n```.

**Comment by DanielLiamAnderson** [comment]
Ah, I see.  `parlay::sequence` is not designed to support concurrent `push_back`.

You will either need to take a lock, use something like a linked list, or try something like TBB's `concurrent_vector` (https://spec.oneapi.io/versions/latest/elements/oneTBB/source/containers/concurrent_vector_cls.html)
