### ISSUE TITLE
Busy waiting in homegrown scheduler when no jobs are spawned

### ISSUE THREAD

**Issue by anivegesana** [cmuparlay/parlaylib#33]
Happy new year, all!

Below are the relevant lines of code in the homegrown scheduler.
https://github.com/cmuparlay/parlaylib/blob/6302233a72199b9a0f69e4bdb63928ebf5e8f3cc/include/parlay/scheduler.h#L258-L268

When all deques are empty, `try_steal` will always fail and this loop repeats indefinitely. In each iteration, it will sleep for a short amount of time and wake up again only to fall asleep without doing any computation. The result is high CPU usage despite no actual work being performed.

```c++
#include <iostream>

#include <parlay/scheduler.h>

using namespace std;

int main() {
  parlay::fork_join_scheduler fj;
  int x = 0, y = 0;
  
  cout << "Please enter two integer values: ";
  cin >> x >> y;

  fj.pardo(
    [&]() { x += 1; },
    [&]() { y += 2; }
  );

  cout << x << " " << y << endl;
  return 0;
}
```
Instead of waiting for a fixed amount of time, the scheduler should wait until a deque is (potentially) nonempty.

**Comment by DanielLiamAnderson** [comment]
Fixed by #52.
