### ISSUE TITLE
including "parlay/parallel.h" fails to compile on anything but c++17

### ISSUE THREAD

**Issue by wheatman** [cmuparlay/parlaylib#53]
With the following c++ program 

```c++
#include "parlay/parallel.h"

int main() { return 1; }
```

It fails to compile unless I use exactly c++20.

The code compiles if I don't use the most recent commit.

You get the following errors

g++
In file included from ../parlaylib/include/parlay/parallel.h:105,
                 from parlay_test.cpp:1:
../parlaylib/include/parlay/scheduler.h: In member function ‘void parlay::scheduler<Job>::wake_up_a_worker()’:
../parlaylib/include/parlay/scheduler.h:249:32: error: missing template arguments before ‘(’ token
  249 |       parlay::atomic_notify_one(&wake_up_counter);
      |                                ^
../parlaylib/include/parlay/scheduler.h: In member function ‘void parlay::scheduler<Job>::wake_up_all_workers()’:
../parlaylib/include/parlay/scheduler.h:257:32: error: missing template arguments before ‘(’ token
  257 |       parlay::atomic_notify_all(&wake_up_counter);
      |                                ^
../parlaylib/include/parlay/scheduler.h: In member function ‘void parlay::scheduler<Job>::wait_for_work()’:
../parlaylib/include/parlay/scheduler.h:264:24: error: missing template arguments before ‘(’ token
  264 |     parlay::atomic_wait(&wake_up_counter, wake_up_counter.load());

clang++
In file included from parlay_test.cpp:1:
In file included from ../parlaylib/include/parlay/parallel.h:105:
../parlaylib/include/parlay/scheduler.h:249:15: error: use of variable template 'atomic_notify_one' requires template arguments
      parlay::atomic_notify_one(&wake_up_counter);
              ^
../parlaylib/include/parlay/internal/atomic_wait.h:401:16: note: template is declared here
    const auto atomic_notify_one = std::atomic_notify_one<_Tp>;
               ^
In file included from parlay_test.cpp:1:
In file included from ../parlaylib/include/parlay/parallel.h:105:
../parlaylib/include/parlay/scheduler.h:257:15: error: use of variable template 'atomic_notify_all' requires template arguments
      parlay::atomic_notify_all(&wake_up_counter);
              ^
../parlaylib/include/parlay/internal/atomic_wait.h:404:16: note: template is declared here
    const auto atomic_notify_all = std::atomic_notify_all<_Tp>;
               ^
In file included from parlay_test.cpp:1:
In file included from ../parlaylib/include/parlay/parallel.h:105:
../parlaylib/include/parlay/scheduler.h:264:13: error: use of variable template 'atomic_wait' requires template arguments
    parlay::atomic_wait(&wake_up_counter, wake_up_counter.load());
            ^
../parlaylib/include/parlay/internal/atomic_wait.h:398:16: note: template is declared here
    const auto atomic_wait = std::atomic_wait<_Tp, _Tv>;
               ^
3 errors generated.

**Comment by DanielLiamAnderson** [comment]
Could you please provide the exact compiler version you are using (`g++ --version` and `clang++ --version`), the OS version, and the exact commands that you are using to compile the code?

**Comment by wheatman** [comment]
clang++ -I../parlaylib/include -std=c++20 parlay_test.cpp 

clang++ --version
Ubuntu clang version 14.0.0-1ubuntu1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

g++ -I../parlaylib/include -std=c++20 parlay_test.cpp

g++ --version
g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


also, I have a fix.
in atomic_wait.h at the bottomr, you use a different numbers of template arguments as what I am seeing on https://en.cppreference.com/w/cpp/atomic/atomic_notify_one

after fixing those I just specified the template parameters in scheduler.h and it seems to fix the issue.

Here is the full diff

diff --git a/include/parlay/internal/atomic_wait.h b/include/parlay/internal/atomic_wait.h
index d86550b..d0ec834 100644
--- a/include/parlay/internal/atomic_wait.h
+++ b/include/parlay/internal/atomic_wait.h
@@ -355,21 +355,21 @@ __ABI void __cxx_atomic_wait(_Tp const* ptr, _Tp const val, int order) {
 
 namespace parlay {
 
-    template <class _Tp, class _Tv>
-    __ABI void atomic_wait_explicit(std::atomic<_Tp> const* a, _Tv val, std::memory_order order) {
-        __cxx_atomic_wait((const _Tp*)a, (_Tp)val, (int)order);   // cppcheck-suppress cstyleCast
+    template <class _T>
+    __ABI void atomic_wait_explicit(std::atomic<_T> const* a, typename std::atomic<_T>::value_type val, std::memory_order order) {
+        __cxx_atomic_wait((const _T*)a, (_T)val, (int)order);   // cppcheck-suppress cstyleCast
     }
-    template <class _Tp, class _Tv>
-    __ABI void atomic_wait(std::atomic<_Tp> const* a, _Tv val) {
+    template <class _T>
+    __ABI void atomic_wait(std::atomic<_T> const* a, typename std::atomic<_T>::value_type val) {
         parlay::atomic_wait_explicit(a, val, std::memory_order_seq_cst);
     }
-    template <class _Tp>
-    __ABI void atomic_notify_one(std::atomic<_Tp> const* a) {
-        __cxx_atomic_notify_one((const _Tp*)a);                   // cppcheck-suppress cstyleCast
+    template <class _T>
+    __ABI void atomic_notify_one(std::atomic<_T> const* a) {
+        __cxx_atomic_notify_one((const _T*)a);                   // cppcheck-suppress cstyleCast
     }
-    template <class _Tp>
-    __ABI void atomic_notify_all(std::atomic<_Tp> const* a) {
-        __cxx_atomic_notify_all((const _Tp*)a);                   // cppcheck-suppress cstyleCast
+    template <class _T>
+    __ABI void atomic_notify_all(std::atomic<_T> const* a) {
+        __cxx_atomic_notify_all((const _T*)a);                   // cppcheck-suppress cstyleCast
     }
 
 }
@@ -391,17 +391,17 @@ extern inline contended_t * __contention(volatile void const * p) {
 
 namespace parlay {
 
-    template <class _Tp, class _Tv>
-    const auto atomic_wait_explicit = std::atomic_wait_explicit<_Tp, _Tv>;
+    template <class _T>
+    const auto atomic_wait_explicit = std::atomic_wait_explicit<_T>;
 
-    template <class _Tp, class _Tv>
-    const auto atomic_wait = std::atomic_wait<_Tp, _Tv>;
+    template <class _T>
+    const auto atomic_wait = std::atomic_wait<_T>;
 
-    template <class _Tp>
-    const auto atomic_notify_one = std::atomic_notify_one<_Tp>;
+    template <class _T>
+    const auto atomic_notify_one = std::atomic_notify_one<_T>;
 
-    template <class _Tp>
-    const auto atomic_notify_all = std::atomic_notify_all<_Tp>;
+    template <class _T>
+    const auto atomic_notify_all = std::atomic_notify_all<_T>;
 
 }
 
diff --git a/include/parlay/scheduler.h b/include/parlay/scheduler.h
index 5fc882f..c9bdd93 100644
--- a/include/parlay/scheduler.h
+++ b/include/parlay/scheduler.h
@@ -246,7 +246,7 @@ struct scheduler {
   void wake_up_a_worker() {
     if (num_awake_workers.load(std::memory_order_acquire) < num_threads) {
       wake_up_counter.fetch_add(1);
-      parlay::atomic_notify_one(&wake_up_counter);
+      parlay::atomic_notify_one<size_t>(&wake_up_counter);
     }
   }
   
@@ -254,14 +254,14 @@ struct scheduler {
   void wake_up_all_workers() {
     if (num_awake_workers.load(std::memory_order_acquire) < num_threads) {
       wake_up_counter.fetch_add(1);
-      parlay::atomic_notify_all(&wake_up_counter);
+      parlay::atomic_notify_all<size_t>(&wake_up_counter);
     }
   }
   
   // Wait until notified to wake up
   void wait_for_work() {
     num_awake_workers.fetch_sub(1);
-    parlay::atomic_wait(&wake_up_counter, wake_up_counter.load());
+    parlay::atomic_wait<size_t>(&wake_up_counter, wake_up_counter.load());
     num_awake_workers.fetch_add(1);
   }

**Comment by DanielLiamAnderson** [comment]
Thanks for looking into this!  This should now be fixed by #55.  Please let me know if it still fails for you.
