### ISSUE TITLE
Does `sequence` skip default initialization

### ISSUE THREAD

**Issue by WhateverLiu** [cmuparlay/parlaylib#75]
The `parlay::allocator` is really fast already. I want to make sure that it will skip default initialization if the element type is primitive, i.e. https://stackoverflow.com/a/21028912/2961927 . But by browsing the codebase it appears `sequence` already has this feature or something similar (`internal/sequence_base.h`) ?:
```
 if constexpr (is_trivial_allocator_v<T_allocator_type, T>) {
          parlay::uninitialized_relocate_n(current_buffer, n, dest_buffer);
        }
        else {
          parallel_for(0, n, [&](size_t i){
            std::allocator_traits<T_allocator_type>::construct(
              alloc, std::addressof(dest_buffer[i]), std::move(current_buffer[i]));
            std::allocator_traits<T_allocator_type>::destroy(
              alloc, std::addressof(current_buffer[i]));
          });
        }
```

**Comment by DanielLiamAnderson** [comment]
I don't really understand the question. The allocator does not initialize any elements regardless of their type, it just provides uninitialized memory for containers.

The code that you are quoting is for relocating elements when the sequence is resized, and is casing on whether the allocator is trivial (which Parlay allocator, and 99% of other allocators are), which is unrelated to whether the element type `T` is primitive.

**Comment by WhateverLiu** [comment]
Thank you Daniel. The question was poorly written before I tested it myself. So later I found that, say just by declaring `parlay::sequence<double> x(1e6)`, all the elements of `x` will be initialized to 0. This is fair since `sequence` is supposed to behave the same as `std::vector`.

What I wanted is to let `parlay::sequence<double> x(1e6)` not populate the buffer and pollute the cache, if the sequence stores some primitive type. The SO post solves that problem.

But by adding a `construct()` member function to `parlay::allocator` as I did to other allocators, a compile error suddenly pops up and I don't know how to solve it. Thus my new post here: https://github.com/cmuparlay/parlaylib/issues/76

Please feel free to close this issue if you think appropriate.
