### ISSUE TITLE
Is sample_sort_inplace really inplace?

### ISSUE THREAD

**Issue by larsgottesbueren** [cmuparlay/parlaylib#80]
Given that this line https://github.com/cmuparlay/parlaylib/blob/master/include/parlay/internal/sample_sort.h#L162 seems to allocate n elements, is the sort_inplace function really inplace? Am I missing something? To me, inplace doesn't necessarily mean "use no additional memory", but it certainly means "do not use additional memory proportional to the input". I'm well aware that an in-place parallel sample sort is non-trivial. What are your thoughts on either reflecting this in the documentation, or potentially using parts of https://github.com/ips4o/ips4o -- without the custom task scheduling etc., obviously.

**Comment by WhateverLiu** [comment]
https://github.com/cmuparlay/parlaylib/issues/47#issuecomment-1461091291 could be related.

**Comment by gblelloch** [comment]
Yes, #47 is definitely related.   We updated the documentation a while ago to try to make this clear.  In particular it reads: 
"Note that the inplace functions may still allocate additional temporary memory. They are not guaranteed to use no memory."  
Note that "inplace" is a "technical" term meaning it does not call the copy constructor and hence the elements need not be copyable.   It is unfortunate it coincides with the algorithmic notion of inplace.
